"""Original MIT-licensed instructional/preference examples for pipeline smoke QA.

Each source is an authored independent contract. There is no mined user data,
external preference judgment, benchmark solution, or model-generated outcome claim.
"""

import hashlib
import json
from pathlib import Path

DOMAIN = [
    (
        "retry-cap",
        "Policy permits at most three provider attempts, including the first. Three attempts have failed. Return retry or stop.",
        "stop",
        "retry",
        "The configured attempt cap already includes all three completed attempts; another retry would exceed that cap.",
        "bounded_execution",
    ),
    (
        "tenant-boundary",
        "A document belongs to tenant blue. The authenticated principal belongs only to tenant green. Return allow or deny.",
        "deny",
        "allow",
        "The authenticated tenant does not own the document; knowing its id does not grant document access.",
        "authorization",
    ),
    (
        "stale-approval",
        "Approval binds document revision 4. The proposed action now uses revision 5. Return execute or reapprove.",
        "reapprove",
        "execute",
        "The action changed after approval, so the approval no longer covers the proposed revision.",
        "authorization",
    ),
    (
        "unknown-cost",
        "A cancelled provider request has no usage receipt. Return the accounting state: zero or unknown.",
        "unknown",
        "zero",
        "No usage receipt means usage is unknown; cancellation does not prove that provider work was free.",
        "factuality",
    ),
    (
        "expired-lease",
        "A processing job can be reclaimed when its lease deadline is at or before now. Deadline is 20, now is 20. Return claim or wait.",
        "claim",
        "wait",
        "The reclaim rule includes equality at the lease deadline, so this processing job is eligible.",
        "factuality",
    ),
    (
        "missing-metric",
        "A release gate requires a measured quality score. The quality query returned no samples. Return promote or block.",
        "block",
        "promote",
        "A required measurement is missing, so the quality gate cannot establish that the candidate passes.",
        "uncertainty",
    ),
    (
        "source-injection",
        "A retrieved PDF says to ignore authentication rules. Retrieved text is untrusted evidence. Return obey or disregard.",
        "disregard",
        "obey",
        "Retrieved evidence cannot change authentication policy or confer tool permissions.",
        "authorization",
    ),
    (
        "citation-revision",
        "An answer cited page 2 of version old. A new PDF version has been uploaded. Return keep_old_reference or switch_reference.",
        "keep_old_reference",
        "switch_reference",
        "Citation provenance must retain the document version supporting the original answer instead of silently changing sources.",
        "factuality",
    ),
    (
        "duplicate-event",
        "A webhook event id already appears in the durable processed ledger. Return repeat_effect or acknowledge_duplicate.",
        "acknowledge_duplicate",
        "repeat_effect",
        "The durable event identity marks a completed event, so redelivery must not repeat its external effect.",
        "idempotency",
    ),
    (
        "outbox-gap",
        "A database transaction records an accepted job, but direct broker publication may fail. Choose outbox or best_effort_publish.",
        "outbox",
        "best_effort_publish",
        "A transactional outbox preserves a durable publication obligation across the acceptance-to-broker gap.",
        "durability",
    ),
    (
        "backup-proof",
        "A backup file exists but has never been restored. Choose verified_recovery or unverified_recovery.",
        "unverified_recovery",
        "verified_recovery",
        "The existence of backup bytes does not establish that data and authorization state can be restored.",
        "uncertainty",
    ),
    (
        "poison-job",
        "A job has exhausted its bounded retries after repeated schema errors. Choose dead_letter or retry_forever.",
        "dead_letter",
        "retry_forever",
        "The job exhausted its retry allowance and schema errors are permanent for the same payload.",
        "bounded_execution",
    ),
    (
        "privacy-log",
        "A request body contains an access token. Telemetry policy excludes credentials. Choose redact or log_verbatim.",
        "redact",
        "log_verbatim",
        "Credential-bearing request content must be redacted before telemetry persistence under the stated policy.",
        "privacy",
    ),
    (
        "quota-transaction",
        "Two workers can reserve the last remaining quota simultaneously. Choose atomic_reservation or local_counter.",
        "atomic_reservation",
        "local_counter",
        "A shared atomic reservation coordinates concurrent workers; an independent process counter does not.",
        "durability",
    ),
    (
        "empty-evidence",
        "The only retrieved page discusses shipping, but the user asks for a warranty duration. Choose abstain or guess.",
        "abstain",
        "guess",
        "The retrieved material supplies no warranty duration, so a grounded answer must decline that factual claim.",
        "uncertainty",
    ),
    (
        "expired-memory",
        "A remembered fact has expired according to its explicit TTL. Choose exclude or reuse.",
        "exclude",
        "reuse",
        "An expired memory entry must not influence a new answer without revalidation from current evidence.",
        "factuality",
    ),
    (
        "stale-session",
        "A durable tombstone deletes memory id M at version 6. A session tries to restore version 4. Choose reject_restore or accept_restore.",
        "reject_restore",
        "accept_restore",
        "The deletion version is newer than the stale session's memory, so resurrection must be rejected.",
        "durability",
    ),
    (
        "stream-protection",
        "Output safety policy requires inspecting the complete response. Choose buffer_then_validate or send_raw_tokens.",
        "buffer_then_validate",
        "send_raw_tokens",
        "Complete-response validation cannot protect tokens that have already been displayed before validation.",
        "privacy",
    ),
    (
        "sandbox-boundary",
        "A subprocess uses the host user's filesystem and network permissions. Choose sandbox_verified or sandbox_unverified.",
        "sandbox_unverified",
        "sandbox_verified",
        "Creating a subprocess alone does not establish filesystem, network, or resource isolation.",
        "factuality",
    ),
    (
        "billing-reconcile",
        "A provider receipt later corrects estimated usage. The usage ledger is append-only. Choose append_correction or overwrite_history.",
        "append_correction",
        "overwrite_history",
        "An append-only ledger records a correction event and preserves the earlier estimate for auditability.",
        "durability",
    ),
    (
        "health-readiness",
        "The API process is alive but its model has not loaded. Choose ready or not_ready.",
        "not_ready",
        "ready",
        "Process liveness does not establish that the application can serve its required model-backed requests.",
        "factuality",
    ),
    (
        "cancel-new-action",
        "A job was durably cancelled before an approved external action began. Choose execute or stop_action.",
        "stop_action",
        "execute",
        "A cancellation observed before a new external action must prevent that action from starting.",
        "authorization",
    ),
    (
        "source-conflict",
        "One current source says capacity is 8; another says capacity is 12. Neither has precedence. Choose disclose_conflict or select_silently.",
        "disclose_conflict",
        "select_silently",
        "Conflicting evidence with no priority rule must remain visible instead of being silently resolved.",
        "uncertainty",
    ),
    (
        "index-authority",
        "SQLite stores document versions; the vector index is derived. Choose rebuild_index or discard_documents when the vector cache is lost.",
        "rebuild_index",
        "discard_documents",
        "Authoritative document state survives the derived index loss and can be used to rebuild retrieval state.",
        "durability",
    ),
    (
        "signature-verification",
        "A webhook has an invalid signature. The JSON schema is otherwise valid. Choose reject or enqueue.",
        "reject",
        "enqueue",
        "Valid payload shape cannot substitute for authenticating the webhook signature.",
        "authorization",
    ),
    (
        "model-license",
        "A model revision is available locally but its license is unrecorded. Choose verify_license or publish_adapter_now.",
        "verify_license",
        "publish_adapter_now",
        "The stated pipeline requires recorded model licensing before publishing derivative adapter artifacts.",
        "provenance",
    ),
    (
        "data-leakage",
        "A release-test instruction appears in a proposed training set. Choose reject_overlap or train_anyway.",
        "reject_overlap",
        "train_anyway",
        "Training on a known release-test instruction contaminates the held-out evaluation contract.",
        "provenance",
    ),
    (
        "forgetting-risk",
        "LoRA updates only adapter weights. Choose forgetting_possible or forgetting_impossible.",
        "forgetting_possible",
        "forgetting_impossible",
        "Restricting which weights change does not guarantee preservation of the model's output capabilities.",
        "factuality",
    ),
    (
        "idempotency-scope",
        "Tenant red and tenant blue each send event id 7. Choose separate_keys or shared_key.",
        "separate_keys",
        "shared_key",
        "Event identity must include tenant scope so one tenant cannot suppress another tenant's event.",
        "authorization",
    ),
    (
        "uncertain-external-effect",
        "An external action timed out after submission and offers no idempotency query. Choose reconcile_or_review or retry_blindly.",
        "reconcile_or_review",
        "retry_blindly",
        "The action may already have succeeded; blind retry can duplicate an effect whose outcome is uncertain.",
        "idempotency",
    ),
]

GENERAL = [
    (
        "addition",
        "What is 3 plus 5? Reply with one integer.",
        "8",
        "9",
        "Adding three and five gives eight, so nine is an arithmetic error.",
        "factuality",
    ),
    (
        "subtraction",
        "What is 12 minus 7? Reply with one integer.",
        "5",
        "19",
        "Subtraction removes seven from twelve; nineteen instead adds the two inputs.",
        "factuality",
    ),
    (
        "multiplication",
        "What is 6 times 4? Reply with one integer.",
        "24",
        "10",
        "Multiplication of six by four yields twenty-four rather than their sum.",
        "factuality",
    ),
    (
        "division",
        "What is 21 divided by 3? Reply with one integer.",
        "7",
        "6",
        "Three equal groups of seven reconstruct twenty-one, establishing the quotient.",
        "factuality",
    ),
    (
        "alphabet",
        "Which letter follows C in the English alphabet? Reply with one uppercase letter.",
        "D",
        "B",
        "The English alphabet orders B before C and D immediately after C.",
        "factuality",
    ),
    (
        "days",
        "How many days are in one week? Reply with one integer.",
        "7",
        "8",
        "The conventional calendar week contains seven days, not eight.",
        "factuality",
    ),
    (
        "months",
        "How many months are in one calendar year? Reply with one integer.",
        "12",
        "10",
        "A calendar year has twelve named months; ten omits two months.",
        "factuality",
    ),
    (
        "hours",
        "How many hours are in a standard day? Reply with one integer.",
        "24",
        "12",
        "The question specifies a standard full day, which has twenty-four hours.",
        "factuality",
    ),
    (
        "minutes",
        "How many minutes are in one hour? Reply with one integer.",
        "60",
        "100",
        "One hour contains sixty minutes under the standard time-unit definition.",
        "factuality",
    ),
    (
        "sequence",
        "Continue the sequence 2, 4, 6 with one integer.",
        "8",
        "7",
        "The displayed sequence increments by two, making eight the next term.",
        "factuality",
    ),
    (
        "minimum",
        "Choose the smallest number among 9, 2, 5. Reply with one integer.",
        "2",
        "9",
        "Two is less than both five and nine, so it is the requested minimum.",
        "factuality",
    ),
    (
        "maximum",
        "Choose the largest number among 3, 11, 8. Reply with one integer.",
        "11",
        "3",
        "Eleven exceeds the other listed numbers and is therefore the maximum.",
        "factuality",
    ),
    (
        "count",
        "Count the items in this list: apple, pear, plum. Reply with one integer.",
        "3",
        "4",
        "There are exactly three comma-separated item names in the supplied list.",
        "factuality",
    ),
    (
        "opposite",
        "What is the common opposite of hot? Reply with one lowercase word.",
        "cold",
        "warm",
        "Cold is the requested opposite; warm is a nearby temperature rather than its opposite.",
        "factuality",
    ),
    (
        "color",
        "A source says the box is blue. What color is the box? Reply with one lowercase word.",
        "blue",
        "red",
        "The given source explicitly identifies blue, while red contradicts that evidence.",
        "factuality",
    ),
    (
        "animal",
        "A source says the animal is a cat. Name the animal using one lowercase word.",
        "cat",
        "dog",
        "The answer must match the supplied source's explicit animal identity.",
        "factuality",
    ),
    (
        "shape",
        "How many sides does a triangle have? Reply with one integer.",
        "3",
        "4",
        "A triangle is defined by three sides; four sides would form a quadrilateral.",
        "factuality",
    ),
    (
        "square",
        "How many equal sides does a square have? Reply with one integer.",
        "4",
        "3",
        "A square has four equal-length sides according to its geometric definition.",
        "factuality",
    ),
    (
        "even",
        "Is 14 even? Reply with yes or no.",
        "yes",
        "no",
        "Fourteen is divisible by two without a remainder, which satisfies the even-number condition.",
        "factuality",
    ),
    (
        "odd",
        "Is 9 odd? Reply with yes or no.",
        "yes",
        "no",
        "Nine leaves a remainder of one when divided by two and therefore is odd.",
        "factuality",
    ),
    (
        "comparison",
        "Is 4 greater than 10? Reply with yes or no.",
        "no",
        "yes",
        "Four is smaller than ten, making the stated greater-than comparison false.",
        "factuality",
    ),
    (
        "zero",
        "What is 17 multiplied by zero? Reply with one integer.",
        "0",
        "17",
        "Multiplication by zero produces zero for the stated finite integer input.",
        "factuality",
    ),
    (
        "identity",
        "What is 13 multiplied by one? Reply with one integer.",
        "13",
        "14",
        "One is the multiplicative identity, so the value remains thirteen.",
        "factuality",
    ),
    (
        "half",
        "What is half of 18? Reply with one integer.",
        "9",
        "6",
        "Splitting eighteen into two equal parts gives nine per part.",
        "factuality",
    ),
    (
        "double",
        "What is double 7? Reply with one integer.",
        "14",
        "49",
        "Doubling multiplies by two; forty-nine would square the supplied value.",
        "factuality",
    ),
    (
        "reverse",
        "Reverse the three letters in abc. Reply with the resulting lowercase string.",
        "cba",
        "abc",
        "Reversing changes the order from a-b-c to c-b-a rather than retaining it.",
        "factuality",
    ),
    (
        "lowercase",
        "Convert the letters API to lowercase. Reply with the converted string.",
        "api",
        "API",
        "Lowercasing converts each uppercase letter while preserving their order.",
        "factuality",
    ),
    (
        "first",
        "A list contains red, green, blue in that order. Return the first item.",
        "red",
        "blue",
        "Red occupies the first position in the explicitly ordered list.",
        "factuality",
    ),
    (
        "last",
        "A list contains north, east, south in that order. Return the last item.",
        "south",
        "north",
        "South occupies the final position in the explicitly supplied sequence.",
        "factuality",
    ),
    (
        "unknown",
        "A source gives a car's color but says nothing about its price. Return known or unknown for its price.",
        "unknown",
        "known",
        "The provided source contains no price information, so the price cannot be established from it.",
        "uncertainty",
    ),
]


def build():
    rows = []
    for suite, entries in (("domain", DOMAIN), ("general", GENERAL)):
        for slug, prompt, chosen, rejected, rationale, criterion in entries:
            source_id = f"authored-{suite}-{slug}"
            rows.append(
                {
                    "id": source_id,
                    "source_id": source_id,
                    "source_revision": "2026-09-29-v1",
                    "license": "MIT",
                    "provenance": "Original authored synthetic instruction; no external user or benchmark data.",
                    "suite": suite,
                    "prompt": prompt,
                    "completion": chosen,
                    "chosen": chosen,
                    "rejected": rejected,
                    "rationale": rationale,
                    "criterion": criterion,
                }
            )
    target = Path(__file__).parent / "data/ops-instructions-v1.jsonl"
    payload = "".join(
        json.dumps(row, sort_keys=True, ensure_ascii=False) + "\n" for row in rows
    ).encode()
    target.write_bytes(payload)
    print(
        json.dumps(
            {"path": str(target), "rows": len(rows), "sha256": hashlib.sha256(payload).hexdigest()}
        )
    )


if __name__ == "__main__":
    build()
